version: '3.9'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE_LISTENER://kafka:9092,OUTSIDE_LISTENER://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE_LISTENER:PLAINTEXT,OUTSIDE_LISTENER:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE_LISTENER
    ports:
      - 9092:9092
      - 29092:29092
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-ui:
    container_name: kafka-ui
    depends_on:
      - kafka
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8081:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    volumes:
      - ~/kui/config.yml:/etc/kafkaui/dynamic_config.yaml

  postgres:
    image: postgres:latest
    container_name: postgres-metastore
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  metastore:
    image: apache/hive:4.0.0
    container_name: hive-metastore
    depends_on:
      - postgres
    environment:
      HIVE_METASTORE_USER: hive
      HIVE_METASTORE_PASSWORD: hive
      HIVE_METASTORE_JDBC_URL: jdbc:postgresql://postgres:5432/metastore
      SERVICE_PORT: 9083
      SERVICE_NAME: "metastore"
    ports:
      - "9083:9083"
    volumes:
      - ./conf:/hive_custom_conf
    command: >
      bash -c "
      wget https://repo1.maven.org/maven2/org/postgresql/postgresql/42.5.1/postgresql-42.5.1.jar -P /opt/hive/lib &&
      schematool -dbType postgres -initSchema;
      hive"

volumes:
  postgres_data:
  metastore_data:
  zookeeper_data:
  zookeeper_datalog:
  kafka_data:
